from __future__ import annotations

from pathlib import Path

import pandas as pd

from uci_points_model.team_depth_features import build_team_depth_panel


def _write_csv(path: Path, rows: list[dict[str, object]], columns: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(rows, columns=columns).to_csv(path, index=False)


def _build_import_root(import_root: Path) -> None:
    _write_csv(
        import_root / "historical_proteam_team_panel.csv",
        [
            {
                "season_year": 2021,
                "team_name": "Team A 2021",
                "team_slug": "team-a-2021",
                "team_class": "PRT",
                "team_rank": 6,
                "team_total_uci_points": 590.0,
                "top1_share": 200.0 / 590.0,
                "top3_share": 470.0 / 590.0,
                "top5_share": 570.0 / 590.0,
                "n_riders_100": 3,
                "n_riders_150": 2,
                "n_riders_250": 0,
                "n_riders_400": 0,
                "avg_points_per_raceday": 3.0,
                "median_points_per_raceday": 1.0,
                "team_points_per_rider_raceday": 3.5,
                "archetype_anchor_count": 1,
                "archetype_engine_count": 2,
                "archetype_banker_count": 0,
            },
            {
                "season_year": 2022,
                "team_name": "Team A 2022",
                "team_slug": "team-a-2022",
                "team_class": "PRT",
                "team_rank": 4,
                "team_total_uci_points": 490.0,
                "top1_share": 300.0 / 490.0,
                "top3_share": 440.0 / 490.0,
                "top5_share": 1.0,
                "n_riders_100": 1,
                "n_riders_150": 1,
                "n_riders_250": 1,
                "n_riders_400": 0,
                "avg_points_per_raceday": 4.0,
                "median_points_per_raceday": 1.2,
                "team_points_per_rider_raceday": 4.2,
                "archetype_anchor_count": 1,
                "archetype_engine_count": 1,
                "archetype_banker_count": 1,
            },
        ],
        [
            "season_year",
            "team_name",
            "team_slug",
            "team_class",
            "team_rank",
            "team_total_uci_points",
            "top1_share",
            "top3_share",
            "top5_share",
            "n_riders_100",
            "n_riders_150",
            "n_riders_250",
            "n_riders_400",
            "avg_points_per_raceday",
            "median_points_per_raceday",
            "team_points_per_rider_raceday",
            "archetype_anchor_count",
            "archetype_engine_count",
            "archetype_banker_count",
        ],
    )
    team_panel_path = import_root / "historical_proteam_team_panel.csv"
    team_panel_df = pd.read_csv(team_panel_path)
    filler_team_rows = pd.DataFrame(
        [
            {
                "season_year": season,
                "team_name": f"Team A {season}",
                "team_slug": f"team-a-{season}",
                "team_class": "PRT",
                "team_rank": 5,
                "team_total_uci_points": 100.0,
                "top1_share": 1.0,
                "top3_share": 1.0,
                "top5_share": 1.0,
                "n_riders_100": 1,
                "n_riders_150": 0,
                "n_riders_250": 0,
                "n_riders_400": 0,
                "avg_points_per_raceday": 2.0,
                "median_points_per_raceday": 2.0,
                "team_points_per_rider_raceday": 2.0,
                "archetype_anchor_count": 1,
                "archetype_engine_count": 0,
                "archetype_banker_count": 0,
            }
            for season in range(2023, 2027)
        ]
    )
    pd.concat([team_panel_df, filler_team_rows], ignore_index=True).to_csv(team_panel_path, index=False)
    _write_csv(
        import_root / "historical_proteam_rider_panel.csv",
        [
            {
                "season_year": 2021,
                "team_name": "Team A 2021",
                "team_slug": "team-a-2021",
                "team_class": "PRT",
                "rider_name": "Rider 1",
                "rider_slug": "r1",
                "uci_points": 200.0,
                "pcs_points": 0.0,
                "racedays": 50.0,
                "wins": 0.0,
                "points_per_raceday": 4.0,
                "team_total_uci_points": 590.0,
                "team_rank_within_roster": 1,
                "team_points_share": 200.0 / 590.0,
                "archetype": "anchor",
                "source_points_url": "",
                "source_racedays_url": "",
                "scraped_at": "2026-04-20T00:00:00+00:00",
                "parse_status": "ok",
            },
            {
                "season_year": 2021,
                "team_name": "Team A 2021",
                "team_slug": "team-a-2021",
                "team_class": "PRT",
                "rider_name": "Rider 2",
                "rider_slug": "r2",
                "uci_points": 150.0,
                "pcs_points": 0.0,
                "racedays": 50.0,
                "wins": 0.0,
                "points_per_raceday": 3.0,
                "team_total_uci_points": 590.0,
                "team_rank_within_roster": 2,
                "team_points_share": 150.0 / 590.0,
                "archetype": "engine",
                "source_points_url": "",
                "source_racedays_url": "",
                "scraped_at": "2026-04-20T00:00:00+00:00",
                "parse_status": "ok",
            },
            {
                "season_year": 2021,
                "team_name": "Team A 2021",
                "team_slug": "team-a-2021",
                "team_class": "PRT",
                "rider_name": "Rider 3",
                "rider_slug": "r3",
                "uci_points": 120.0,
                "pcs_points": 0.0,
                "racedays": 50.0,
                "wins": 0.0,
                "points_per_raceday": 2.4,
                "team_total_uci_points": 590.0,
                "team_rank_within_roster": 3,
                "team_points_share": 120.0 / 590.0,
                "archetype": "engine",
                "source_points_url": "",
                "source_racedays_url": "",
                "scraped_at": "2026-04-20T00:00:00+00:00",
                "parse_status": "ok",
            },
            {
                "season_year": 2021,
                "team_name": "Team A 2021",
                "team_slug": "team-a-2021",
                "team_class": "PRT",
                "rider_name": "Rider 4",
                "rider_slug": "r4",
                "uci_points": 60.0,
                "pcs_points": 0.0,
                "racedays": 50.0,
                "wins": 0.0,
                "points_per_raceday": 1.2,
                "team_total_uci_points": 590.0,
                "team_rank_within_roster": 4,
                "team_points_share": 60.0 / 590.0,
                "archetype": "banker",
                "source_points_url": "",
                "source_racedays_url": "",
                "scraped_at": "2026-04-20T00:00:00+00:00",
                "parse_status": "ok",
            },
            {
                "season_year": 2021,
                "team_name": "Team A 2021",
                "team_slug": "team-a-2021",
                "team_class": "PRT",
                "rider_name": "Rider 5",
                "rider_slug": "r5",
                "uci_points": 40.0,
                "pcs_points": 0.0,
                "racedays": 50.0,
                "wins": 0.0,
                "points_per_raceday": 0.8,
                "team_total_uci_points": 590.0,
                "team_rank_within_roster": 5,
                "team_points_share": 40.0 / 590.0,
                "archetype": "banker",
                "source_points_url": "",
                "source_racedays_url": "",
                "scraped_at": "2026-04-20T00:00:00+00:00",
                "parse_status": "ok",
            },
            {
                "season_year": 2021,
                "team_name": "Team A 2021",
                "team_slug": "team-a-2021",
                "team_class": "PRT",
                "rider_name": "Rider 6",
                "rider_slug": "r6",
                "uci_points": 20.0,
                "pcs_points": 0.0,
                "racedays": 50.0,
                "wins": 0.0,
                "points_per_raceday": 0.4,
                "team_total_uci_points": 590.0,
                "team_rank_within_roster": 6,
                "team_points_share": 20.0 / 590.0,
                "archetype": "banker",
                "source_points_url": "",
                "source_racedays_url": "",
                "scraped_at": "2026-04-20T00:00:00+00:00",
                "parse_status": "ok",
            },
            {
                "season_year": 2022,
                "team_name": "Team A 2022",
                "team_slug": "team-a-2022",
                "team_class": "PRT",
                "rider_name": "Rider 7",
                "rider_slug": "r7",
                "uci_points": 300.0,
                "pcs_points": 0.0,
                "racedays": 50.0,
                "wins": 0.0,
                "points_per_raceday": 6.0,
                "team_total_uci_points": 490.0,
                "team_rank_within_roster": 1,
                "team_points_share": 300.0 / 490.0,
                "archetype": "anchor",
                "source_points_url": "",
                "source_racedays_url": "",
                "scraped_at": "2026-04-20T00:00:00+00:00",
                "parse_status": "ok",
            },
            {
                "season_year": 2022,
                "team_name": "Team A 2022",
                "team_slug": "team-a-2022",
                "team_class": "PRT",
                "rider_name": "Rider 8",
                "rider_slug": "r8",
                "uci_points": 90.0,
                "pcs_points": 0.0,
                "racedays": 50.0,
                "wins": 0.0,
                "points_per_raceday": 1.8,
                "team_total_uci_points": 490.0,
                "team_rank_within_roster": 2,
                "team_points_share": 90.0 / 490.0,
                "archetype": "engine",
                "source_points_url": "",
                "source_racedays_url": "",
                "scraped_at": "2026-04-20T00:00:00+00:00",
                "parse_status": "ok",
            },
            {
                "season_year": 2022,
                "team_name": "Team A 2022",
                "team_slug": "team-a-2022",
                "team_class": "PRT",
                "rider_name": "Rider 9",
                "rider_slug": "r9",
                "uci_points": 50.0,
                "pcs_points": 0.0,
                "racedays": 50.0,
                "wins": 0.0,
                "points_per_raceday": 1.0,
                "team_total_uci_points": 490.0,
                "team_rank_within_roster": 3,
                "team_points_share": 50.0 / 490.0,
                "archetype": "engine",
                "source_points_url": "",
                "source_racedays_url": "",
                "scraped_at": "2026-04-20T00:00:00+00:00",
                "parse_status": "ok",
            },
            {
                "season_year": 2022,
                "team_name": "Team A 2022",
                "team_slug": "team-a-2022",
                "team_class": "PRT",
                "rider_name": "Rider 10",
                "rider_slug": "r10",
                "uci_points": 40.0,
                "pcs_points": 0.0,
                "racedays": 50.0,
                "wins": 0.0,
                "points_per_raceday": 0.8,
                "team_total_uci_points": 490.0,
                "team_rank_within_roster": 4,
                "team_points_share": 40.0 / 490.0,
                "archetype": "banker",
                "source_points_url": "",
                "source_racedays_url": "",
                "scraped_at": "2026-04-20T00:00:00+00:00",
                "parse_status": "ok",
            },
            {
                "season_year": 2022,
                "team_name": "Team A 2022",
                "team_slug": "team-a-2022",
                "team_class": "PRT",
                "rider_name": "Rider 11",
                "rider_slug": "r11",
                "uci_points": 10.0,
                "pcs_points": 0.0,
                "racedays": 50.0,
                "wins": 0.0,
                "points_per_raceday": 0.2,
                "team_total_uci_points": 490.0,
                "team_rank_within_roster": 5,
                "team_points_share": 10.0 / 490.0,
                "archetype": "banker",
                "source_points_url": "",
                "source_racedays_url": "",
                "scraped_at": "2026-04-20T00:00:00+00:00",
                "parse_status": "ok",
            },
        ],
        [
            "season_year",
            "team_name",
            "team_slug",
            "team_class",
            "rider_name",
            "rider_slug",
            "uci_points",
            "pcs_points",
            "racedays",
            "wins",
            "points_per_raceday",
            "team_total_uci_points",
            "team_rank_within_roster",
            "team_points_share",
            "archetype",
            "source_points_url",
            "source_racedays_url",
            "scraped_at",
            "parse_status",
        ],
    )
    rider_panel_path = import_root / "historical_proteam_rider_panel.csv"
    rider_panel_df = pd.read_csv(rider_panel_path)
    filler_rider_rows = pd.DataFrame(
        [
            {
                "season_year": season,
                "team_name": f"Team A {season}",
                "team_slug": f"team-a-{season}",
                "team_class": "PRT",
                "rider_name": f"Filler Rider {season}",
                "rider_slug": f"filler-{season}",
                "uci_points": 100.0,
                "pcs_points": 0.0,
                "racedays": 50.0,
                "wins": 0.0,
                "points_per_raceday": 2.0,
                "team_total_uci_points": 100.0,
                "team_rank_within_roster": 1,
                "team_points_share": 1.0,
                "archetype": "anchor",
                "source_points_url": "",
                "source_racedays_url": "",
                "scraped_at": "2026-04-20T00:00:00+00:00",
                "parse_status": "ok",
            }
            for season in range(2023, 2027)
        ]
    )
    pd.concat([rider_panel_df, filler_rider_rows], ignore_index=True).to_csv(rider_panel_path, index=False)
    _write_csv(
        import_root / "transition_continuity_links.csv",
        [
            {
                "year_b": 2022,
                "next_team_slug": "team-a-2022",
                "next_team_name": "Team A 2022",
                "prior_team_slug": "team-a-2021",
                "year_a": 2021,
                "continuity_source": "pcs_prev_link",
                "cache_path": "/tmp/team-a-2022.md",
                "matched_prior_team": 1,
            },
            {
                "year_b": 2023,
                "next_team_slug": "team-a-2023",
                "next_team_name": "Team A 2023",
                "prior_team_slug": "team-a-2022",
                "year_a": 2022,
                "continuity_source": "pcs_prev_link",
                "cache_path": "/tmp/team-a-2023.md",
                "matched_prior_team": 1,
            },
        ],
        [
            "year_b",
            "next_team_slug",
            "next_team_name",
            "prior_team_slug",
            "year_a",
            "continuity_source",
            "cache_path",
            "matched_prior_team",
        ],
    )
    _write_csv(
        import_root / "ranking_predictor_study_data.csv",
        [
            {
                "team": "Team A 2021",
                "prior_team_base": "team-a",
                "year_a": 2021,
                "year_b": 2022,
                "prior_team_slug": "team-a-2021",
                "next_team_slug": "team-a-2022",
                "next_team_name": "Team A 2022",
                "continuity_source": "pcs_prev_link",
                "prior_total_pts": 590.0,
                "prior_rank": 6,
                "prior_n_scorers": 6,
                "prior_n_riders_150": 2,
                "prior_n_riders_250": 0,
                "prior_top1_share": 200.0 / 590.0,
                "prior_top3_share": 470.0 / 590.0,
                "prior_top5_share": 570.0 / 590.0,
                "prior_hhi": 0.0,
                "prior_eff_n": 0.0,
                "prior_gini": 0.0,
                "prior_avg_points_per_raceday": 3.0,
                "prior_team_points_per_rider_raceday": 3.5,
                "prior_archetype_anchor_count": 1,
                "prior_archetype_engine_count": 2,
                "prior_archetype_banker_count": 0,
                "rank_change": -2,
                "pts_change": -100.0,
                "next_rank": 4,
                "next_pts": 490.0,
                "next_top3": 0,
                "next_top5": 1,
                "next_top8": 1,
            }
        ],
        [
            "team",
            "prior_team_base",
            "year_a",
            "year_b",
            "prior_team_slug",
            "next_team_slug",
            "next_team_name",
            "continuity_source",
            "prior_total_pts",
            "prior_rank",
            "prior_n_scorers",
            "prior_n_riders_150",
            "prior_n_riders_250",
            "prior_top1_share",
            "prior_top3_share",
            "prior_top5_share",
            "prior_hhi",
            "prior_eff_n",
            "prior_gini",
            "prior_avg_points_per_raceday",
            "prior_team_points_per_rider_raceday",
            "prior_archetype_anchor_count",
            "prior_archetype_engine_count",
            "prior_archetype_banker_count",
            "rank_change",
            "pts_change",
            "next_rank",
            "next_pts",
            "next_top3",
            "next_top5",
            "next_top8",
        ],
    )


def test_build_team_depth_panel_derives_thresholds_and_targets(tmp_path: Path) -> None:
    import_root = tmp_path / "imported"
    _build_import_root(import_root)

    panel = build_team_depth_panel(import_root=import_root)

    row_2021 = panel.loc[panel["season"] == 2021].iloc[0]
    row_2022 = panel.loc[panel["season"] == 2022].iloc[0]

    assert int(row_2021["n_riders_50_plus"]) == 4
    assert int(row_2021["n_riders_100_plus"]) == 3
    assert int(row_2021["n_riders_150_plus"]) == 2
    assert int(row_2021["n_riders_300_plus"]) == 0
    assert int(row_2021["n_riders_scoring"]) == 6
    assert float(row_2021["points_outside_top5"]) == 20.0
    assert round(float(row_2021["effective_contributors"]), 4) == 4.2194
    assert row_2021["team_base_slug"] == "team-a"
    assert int(row_2021["next_top5_proteam"]) == 1
    assert pd.isna(row_2022["next_top5_proteam"])
    assert row_2022["next_team_slug"] == "team-a-2023"


def test_build_team_depth_panel_keeps_current_season_metrics_in_season_space(tmp_path: Path) -> None:
    import_root = tmp_path / "imported"
    _build_import_root(import_root)
    current_snapshot_df = pd.DataFrame(
        [
            {
                "scope": "current",
                "team_rank": 20,
                "team_name": "Team A 2026",
                "team_slug": "team-a-2026",
                "team_class": "PRT",
                "ranking_total_points": 180.0,
                "team_total_points": 180.0,
                "sanction_points_total": 0.0,
                "season_year": 2026,
                "rider_name": "Leader Rider",
                "rider_slug": "leader-rider",
                "team_rank_within_counted_list": 1,
                "points_counted": 120.0,
                "points_not_counted": 0.0,
                "sanction_points": 0.0,
                "is_placeholder_team_row": False,
            },
            {
                "scope": "current",
                "team_rank": 20,
                "team_name": "Team A 2026",
                "team_slug": "team-a-2026",
                "team_class": "PRT",
                "ranking_total_points": 180.0,
                "team_total_points": 180.0,
                "sanction_points_total": 0.0,
                "season_year": 2026,
                "rider_name": "Support Rider",
                "rider_slug": "support-rider",
                "team_rank_within_counted_list": 2,
                "points_counted": 60.0,
                "points_not_counted": 0.0,
                "sanction_points": 0.0,
                "is_placeholder_team_row": False,
            },
        ]
    )

    panel = build_team_depth_panel(import_root=import_root, current_snapshot_df=current_snapshot_df)

    current_row = panel.loc[(panel["season"] == 2026) & (panel["team_slug"] == "team-a-2026")].iloc[0]
    assert float(current_row["team_points_total"]) == 100.0
    assert int(current_row["n_riders_50_plus"]) == 1
    assert int(current_row["n_riders_100_plus"]) == 1
    assert int(current_row["n_riders_scoring"]) == 1
    assert float(current_row["top1_share"]) == 1.0
